### ISSUE TITLE
Question: 64bit OS on master/worker nodes

### ISSUE THREAD

**Issue by cmonty14** [geerlingguy/turing-pi-cluster#32]
Hello,

can you please share information when 64bit OS on master/worker nodes is required?
In my understanding this depends on the applications that are running on the cluster, right?

I intend to deploy a cluster solution running K8S + [Rancher Longhorn](https://rancher.com/products/longhorn/).
And I think 64bit is required here.

Regards
Thomas

**Comment by geerlingguy** [comment]
I usually run the Pi OS 64-bit beta, it works well and is basically the same as Debian 10 64-bit right now.

Ubuntu 20.04 also comes in a 64-bit variety, and works well, also supporting cloud-init, which is handy.
