### ISSUE TITLE
KubeControllerManagerDown & kubeSchedulerDown

### ISSUE THREAD

**Issue by pduany** [geerlingguy/turing-pi-cluster#34]
Hi
First thing thank you for your content you put up.  I am attempting to build a cluster of 3 Pi 4's  that I ran this script against.  
After getting the monitoring running I am seeing an alert for the KubeController and the Scheduler are down.  I think I have found the solution but have no idea how to apply it can you point me in the right direction?

this is the patch

# kubeadm-patches/kube-controller-manager+json.yaml
- op: add
  path: /spec/containers/0/command/-
  value: --bind-address=SOME_IP
- op: replace
  path: /spec/containers/0/livenessProbe/httpGet/host
  value: SOME_IP
- op: replace
  path: /spec/containers/0/startupProbe/httpGet/host
  value: SOME_IP
  
# kubeadm-patches/kube-scheduler+json.yaml
- op: add
  path: /spec/containers/0/command/-
  value: --bind-address=SOME_IP
- op: replace
  path: /spec/containers/0/livenessProbe/httpGet/host
  value: SOME_IP
- op: replace
  path: /spec/containers/0/startupProbe/httpGet/host
  value: SOME_IP

it was from this GitHub posting
https://github.com/kubernetes/kubeadm/issues/2388
the other one is this
https://github.com/prometheus-operator/kube-prometheus/issues/718

Thanks
Patrick

**Comment by avoidik** [comment]
in kubeadm case these patches intended to change kubernetes manifests before kubeadm starting control-plane configuration step, so you can apply them directly to the yaml files manually using something like [json-patch](https://github.com/evanphx/json-patch) (in other cases at run-time using `kubectl patch`)
