### ISSUE TITLE
i2c help or guidence - powered off all nodes with i2c

### ISSUE THREAD

**Issue by vladvanderwolf** [geerlingguy/turing-pi-cluster#39]
Hi Jeff,
I know this cry for help is long shoot but Im little desparate since i coudnt find any reference on internet
Your idea or guidence is most welcome

By accident i sent command via i2c to shutdown all nodes.
Done so far:
- connected second raspbarry via GPIO i2c (pin3 SDA and pin5 SCL) to Turing external i2C
- via i2c-tools tried i2cdetect but it doesent find any device
- RPi 3B+ OS Bullseye
Clossest description to solution i found here:
https://github.com/nicholaswilde/turing-pi-scripts 
WARNING:The register which controls the power to each board is backed by an EEPROM. Don't set all bits in there to 0, otherwise you won't be able to boot and correct it. A fix is to set register 0xF4 to 1 which would send the writes to the shadow SRAM, instead of the EEPROM. A fix for this is to connect an external raspberry pi to the I2C External pins and reset the registers. |

PS: Im just start learning Kubernetes and Ansible

**Comment by geerlingguy** [comment]
@vladvanderwolf - I would suggest asking about this on the Turing Pi discord: https://discord.com/invite/uNbysyc
